// <auto-generated />
using LegoStore.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LegoStore.Infrastructure.Migrations
{
    [DbContext(typeof(StorageDbContext))]
    partial class StorageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LegoStore.Infrastructure.Entities.CabinetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StorageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StorageId");

                    b.ToTable("Cabinets", (string)null);
                });

            modelBuilder.Entity("LegoStore.Infrastructure.Entities.CaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseGroupId")
                        .HasColumnType("int");

                    b.Property<string>("ContainerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseGroupId");

                    b.ToTable("Cases", (string)null);
                });

            modelBuilder.Entity("LegoStore.Infrastructure.Entities.CaseGroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.ToTable("CaseGroups", (string)null);
                });

            modelBuilder.Entity("LegoStore.Infrastructure.Entities.ContainerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("Containers", (string)null);
                });

            modelBuilder.Entity("LegoStore.Infrastructure.Entities.SectionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContainerId")
                        .HasColumnType("int");

                    b.Property<string>("LotId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.ToTable("Sections", (string)null);
                });

            modelBuilder.Entity("LegoStore.Infrastructure.Entities.StorageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Storages", (string)null);
                });

            modelBuilder.Entity("LegoStore.Infrastructure.Entities.CabinetEntity", b =>
                {
                    b.HasOne("LegoStore.Infrastructure.Entities.StorageEntity", "Storage")
                        .WithMany("Cabinets")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("LegoStore.Infrastructure.Entities.CaseEntity", b =>
                {
                    b.HasOne("LegoStore.Infrastructure.Entities.CaseGroupEntity", "CaseGroup")
                        .WithMany("Cases")
                        .HasForeignKey("CaseGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaseGroup");
                });

            modelBuilder.Entity("LegoStore.Infrastructure.Entities.CaseGroupEntity", b =>
                {
                    b.HasOne("LegoStore.Infrastructure.Entities.CabinetEntity", "Cabinet")
                        .WithMany("Groups")
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabinet");
                });

            modelBuilder.Entity("LegoStore.Infrastructure.Entities.ContainerEntity", b =>
                {
                    b.HasOne("LegoStore.Infrastructure.Entities.CaseEntity", "Case")
                        .WithMany("Containers")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("LegoStore.Infrastructure.Entities.SectionEntity", b =>
                {
                    b.HasOne("LegoStore.Infrastructure.Entities.ContainerEntity", "Container")
                        .WithMany("Sections")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("LegoStore.Infrastructure.Entities.CabinetEntity", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("LegoStore.Infrastructure.Entities.CaseEntity", b =>
                {
                    b.Navigation("Containers");
                });

            modelBuilder.Entity("LegoStore.Infrastructure.Entities.CaseGroupEntity", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("LegoStore.Infrastructure.Entities.ContainerEntity", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("LegoStore.Infrastructure.Entities.StorageEntity", b =>
                {
                    b.Navigation("Cabinets");
                });
#pragma warning restore 612, 618
        }
    }
}
